import * as React from "react";
import Head from "next/head";
import Image from "next/image";
import BetterForm from "../components/BetterForm";
import LifeTable from "../components/LifeTable";
import styles from "../styles/Home.module.scss";

export default function Home() {
  const [weeksLived, setWeeksLived] = React.useState<any>(null);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0"
        />
      </Head>

      <main className={styles.main}>
        {!weeksLived && (
          <BetterForm dateFunction={(val: any) => setWeeksLived(val.weeks)} />
        )}
        {weeksLived && (
          <LifeTable
            weeksLived={weeksLived}
            // yearOfBirth={data?.date?.split("-")[0]}
          />
        )}
      </main>
    </div>
  );
}
